/**
 * AGENTS.md generation — Layer 3a.
 *
 * Renders the Analysis into a lean, confidence-aware AGENTS.md file
 * with pi-onboard section markers for safe partial updates.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Analysis, Preferences } from "./types.ts";

const AGENTS_MD = "AGENTS.md";
const DRAFT_MD = "AGENTS.pi-onboard.draft.md";

/** Marker format for safe section updates. */
const START = (section: string) => `<!-- pi-onboard:START section=${section} -->`;
const END = (section: string) => `<!-- pi-onboard:END section=${section} -->`;

/** Result of a write operation. */
export interface WriteResult {
  path: string;
  action: "created" | "updated" | "draft" | "forced" | "skipped";
}

/**
 * Generate the AGENTS.md content from analysis and preferences.
 */
export function generateAgentsMd(analysis: Analysis, prefs: Preferences): string {
  const concise = prefs.detail === "concise";
  const sections: string[] = [`# AGENTS.md\n\n> Auto-generated by pi-onboard. Review before committing.\n`];

  const has = (id: string) => prefs.sections.includes(id);

  if (has("purpose")) {
    sections.push(section("purpose", [
      `## Project purpose`,
      ``,
      `- **Name:** ${analysis.name}`,
      `- **Purpose:** ${analysis.purpose}`,
      `- **Confidence:** ${analysis.purposeConfidence}`,
    ], prefs));
  }

  if (has("stack") && analysis.stack.length > 0) {
    sections.push(section("stack", [
      `## Tech stack`,
      ``,
      ...analysis.stack.map((s) => `- ${s.name} [${s.confidence}]`),
    ], prefs));
  }

  if (has("paths") && analysis.importantDirs.length > 0) {
    sections.push(section("paths", [
      `## Important paths`,
      ``,
      ...analysis.importantDirs.map((d) =>
        `- \`${d.name}/\`${d.description ? ` — ${d.description}` : ""}`,
      ),
    ], prefs));
  }

  if (has("commands") && analysis.commands.length > 0) {
    const lines = [`## Commands`, ``];
    // Group by label for standard commands, list others
    const standard = analysis.commands.filter((c) =>
      ["Run", "Test", "Lint", "Build"].includes(c.label),
    );
    const others = analysis.commands.filter((c) =>
      !["Run", "Test", "Lint", "Build"].includes(c.label),
    );

    for (const cmd of standard) {
      lines.push(`- **${cmd.label}** (\`${cmd.command}\`) [${cmd.confidence}]`);
    }
    if (others.length > 0 && !concise) {
      lines.push(``);
      for (const cmd of others) {
        lines.push(`- ${cmd.label}: \`${cmd.command}\` [${cmd.confidence}]`);
      }
    }
    sections.push(section("commands", lines, prefs));
  }

  if (has("conventions") && analysis.conventions.length > 0) {
    sections.push(section("conventions", [
      `## Working conventions`,
      ``,
      ...analysis.conventions.map((c) => `- ${c}`),
    ], prefs));
  }

  if (has("where-to-start") && analysis.startingPoints.length > 0) {
    sections.push(section("where-to-start", [
      `## Where to start when making changes`,
      ``,
      ...analysis.startingPoints.map((p, i) => `${i + 1}. Read \`${p}\``),
    ], prefs));
  }

  if (has("uncertainties") && analysis.uncertainties.length > 0) {
    sections.push(section("uncertainties", [
      `## Open uncertainties`,
      ``,
      ...analysis.uncertainties.map((u) => `- ${u}`),
    ], prefs));
  }

  return sections.join("\n\n") + "\n";
}

/**
 * Write AGENTS.md with file-safety:
 * - No file → create.
 * - Exists with markers → update marked sections only.
 * - Exists, no markers, no --force → write draft.
 * - --force → overwrite.
 * - --dry-run → return content without writing.
 */
export function writeAgentsMd(
  cwd: string,
  content: string,
  force: boolean,
  dryRun: boolean,
): WriteResult {
  if (dryRun) {
    return { path: AGENTS_MD, action: "skipped" };
  }

  const target = join(cwd, AGENTS_MD);

  if (!existsSync(target)) {
    writeFileSync(target, content, "utf-8");
    return { path: AGENTS_MD, action: "created" };
  }

  const existing = readFileSync(target, "utf-8");
  const hasMarkers = existing.includes("<!-- pi-onboard:START");

  if (hasMarkers) {
    const updated = mergeMarkedSections(existing, content);
    writeFileSync(target, updated, "utf-8");
    return { path: AGENTS_MD, action: "updated" };
  }

  if (force) {
    writeFileSync(target, content, "utf-8");
    return { path: AGENTS_MD, action: "forced" };
  }

  // No markers, not forced → draft
  const draftPath = join(cwd, DRAFT_MD);
  writeFileSync(draftPath, content, "utf-8");
  return { path: DRAFT_MD, action: "draft" };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a section wrapped in pi-onboard markers. */
function section(id: string, lines: string[], prefs: Preferences): string {
  const content = lines.join("\n");
  return `${START(id)}\n${content}\n${END(id)}`;
}

/**
 * Replace marked sections in existing content with new versions.
 * Preserves everything outside the markers.
 */
function mergeMarkedSections(existing: string, generated: string): string {
  let result = existing;

  // Find all section ids in the generated content
  const sectionIds = [...generated.matchAll(/pi-onboard:START section=(\S+)/g)].map((m) => m[1]);

  for (const id of sectionIds) {
    const startMarker = START(id);
    const endMarker = END(id);

    // Extract new section content (between markers, inclusive)
    const newSectionMatch = generated.match(
      new RegExp(escapeRegex(startMarker) + "[\\s\\S]*?" + escapeRegex(endMarker)),
    );
    if (!newSectionMatch) continue;

    const newSection = newSectionMatch[0];

    // Replace in existing if the markers exist there
    const existingPattern = new RegExp(
      escapeRegex(startMarker) + "[\\s\\S]*?" + escapeRegex(endMarker),
      "g",
    );

    if (existingPattern.test(result)) {
      result = result.replace(existingPattern, newSection);
    } else {
      // Section is new — append at the end
      result = result.trimEnd() + "\n\n" + newSection;
    }
  }

  return result;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
