/**
 * HTML overview generation — Layer 3b.
 *
 * Renders the Analysis into a single self-contained HTML file:
 * dark theme, card-based layout, collapsible sections, confidence badges.
 * No framework, no external dependencies, embedded CSS + minimal inline JS.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Analysis, Preferences } from "./types.ts";

const HTML_FILE = "pi-onboard-overview.html";
const DRAFT_HTML = "pi-onboard-overview.draft.html";
const GEN_MARKER = "<!-- generated by pi-onboard -->";

/** Result of a write operation. */
export interface HtmlWriteResult {
  path: string;
  action: "created" | "updated" | "draft" | "forced" | "skipped";
}

/**
 * Generate the self-contained HTML overview.
 */
export function generateHtml(analysis: Analysis, _prefs: Preferences): string {
  const confidenceColor: Record<string, string> = {
    high: "#4ade80",
    medium: "#facc15",
    low: "#fb923c",
  };

  const stackHtml = analysis.stack
    .map((s) => `<span class="badge" style="border-color:${confidenceColor[s.confidence]}">${esc(s.name)}</span>`)
    .join(" ");

  const dirsHtml = analysis.importantDirs.length > 0
    ? analysis.importantDirs
        .map((d) => `<div class="dir-row"><code>${esc(d.name)}/</code><span>${esc(d.description ?? "")}</span></div>`)
        .join("\n")
    : "<p class=\"muted\">No important directories detected.</p>";

  const commandsHtml = analysis.commands.length > 0
    ? analysis.commands
        .map((c) => `
        <div class="cmd-row">
          <span class="cmd-label">${esc(c.label)}</span>
          <code class="cmd-text">${esc(c.command)}</code>
          <span class="badge" style="border-color:${confidenceColor[c.confidence]}">${c.confidence}</span>
        </div>`)
        .join("")
    : "<p class=\"muted\">No commands detected.</p>";

  const conventionsHtml = analysis.conventions.length > 0
    ? analysis.conventions.map((c) => `<li>${esc(c)}</li>`).join("")
    : '<li class="muted">No conventions detected.</li>';

  const nextStepsHtml = analysis.startingPoints.length > 0
    ? analysis.startingPoints.map((p, i) => `<li><code>${esc(p)}</code></li>`).join("")
    : '<li class="muted">No starting points detected.</li>';

  const uncertaintiesHtml = analysis.uncertainties.length > 0
    ? `<div class="card">
        <div class="card-header" onclick="toggleSection(this)">📋 Open uncertainties</div>
        <div class="card-body">
          <ul>${analysis.uncertainties.map((u) => `<li class="muted">${esc(u)}</li>`).join("")}</ul>
        </div>
      </div>`
    : "";

  return `${GEN_MARKER}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(analysis.name)} — pi-onboard overview</title>
<style>
  :root {
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --muted: #7d8590; --accent: #58a6ff;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, sans-serif;
    background: var(--bg); color: var(--text); line-height: 1.6;
    max-width: 880px; margin: 0 auto; padding: 24px 20px 60px;
  }
  h1 { font-size: 1.6rem; margin-bottom: 4px; }
  .muted { color: var(--muted); }
  .badge {
    display: inline-block; font-size: 0.75rem; padding: 2px 8px;
    border: 1px solid var(--border); border-radius: 12px; margin: 2px;
  }
  .card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 8px; margin-bottom: 16px; overflow: hidden;
  }
  .card-header {
    padding: 12px 16px; font-weight: 600; cursor: pointer;
    user-select: none; display: flex; justify-content: space-between;
    align-items: center; transition: background 0.15s;
  }
  .card-header:hover { background: #1c2128; }
  .card-header::after { content: "▾"; color: var(--muted); font-size: 0.8rem; }
  .card-header.collapsed::after { content: "▸"; }
  .card-body { padding: 12px 16px; }
  .card-body.hidden { display: none; }
  .summary-card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 8px; padding: 20px; margin-bottom: 20px;
  }
  .summary-card .stack { margin-top: 8px; }
  .dir-row, .cmd-row {
    display: flex; align-items: center; gap: 12px;
    padding: 6px 0; border-bottom: 1px solid var(--border);
  }
  .dir-row:last-child, .cmd-row:last-child { border-bottom: none; }
  .dir-row code, .cmd-row code {
    font-family: "SF Mono", Monaco, monospace; font-size: 0.85rem;
    background: #1c2128; padding: 2px 8px; border-radius: 4px;
  }
  .cmd-label { font-weight: 600; min-width: 70px; color: var(--accent); }
  .cmd-text { flex: 1; }
  ul { list-style: none; }
  li { padding: 4px 0; }
  code { font-family: "SF Mono", Monaco, monospace; }
  .footer { text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 30px; }
</style>
</head>
<body>

<div class="summary-card">
  <h1>${esc(analysis.name)}</h1>
  <p class="muted">${esc(analysis.purpose)}</p>
  <p class="muted" style="margin-top:4px">Purpose confidence: <span class="badge" style="border-color:${confidenceColor[analysis.purposeConfidence]}">${analysis.purposeConfidence}</span></p>
  <div class="stack">${stackHtml}</div>
</div>

<div class="card">
  <div class="card-header" onclick="toggleSection(this)">📁 Repo structure</div>
  <div class="card-body">
    ${dirsHtml}
  </div>
</div>

<div class="card">
  <div class="card-header" onclick="toggleSection(this)">⚡ Commands</div>
  <div class="card-body">
    ${commandsHtml}
  </div>
</div>

<div class="card">
  <div class="card-header" onclick="toggleSection(this)">📋 Conventions</div>
  <div class="card-body">
    <ul>${conventionsHtml}</ul>
  </div>
</div>

<div class="card">
  <div class="card-header" onclick="toggleSection(this)">📖 Where to start</div>
  <div class="card-body">
    <ol>${nextStepsHtml}</ol>
  </div>
</div>

${uncertaintiesHtml}

<div class="footer">Generated by <strong>pi-onboard</strong></div>

<script>
function toggleSection(header) {
  const body = header.nextElementSibling;
  header.classList.toggle('collapsed');
  body.classList.toggle('hidden');
}
</script>
</body>
</html>`;
}

/**
 * Write the HTML file with file-safety:
 * - No file → create.
 * - Exists with pi-onboard marker → overwrite.
 * - Exists, no marker, no --force → draft.
 * - --force → overwrite.
 * - --dry-run → skip.
 */
export function writeHtml(
  cwd: string,
  content: string,
  force: boolean,
  dryRun: boolean,
): HtmlWriteResult {
  if (dryRun) {
    return { path: HTML_FILE, action: "skipped" };
  }

  const target = join(cwd, HTML_FILE);

  if (!existsSync(target)) {
    writeFileSync(target, content, "utf-8");
    return { path: HTML_FILE, action: "created" };
  }

  const existing = readFileSync(target, "utf-8");
  const isOurs = existing.includes(GEN_MARKER);

  if (isOurs || force) {
    writeFileSync(target, content, "utf-8");
    return { path: HTML_FILE, action: isOurs && !force ? "updated" : force ? "forced" : "updated" };
  }

  // Not ours, not forced → draft
  const draftPath = join(cwd, DRAFT_HTML);
  writeFileSync(draftPath, content, "utf-8");
  return { path: DRAFT_HTML, action: "draft" };
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
