/**
 * pi-onboard — Pi extension for repository onboarding.
 *
 * The /onboard command does a quick static discovery pass, then fills the
 * editor with a structured prompt for the AI agent. The user presses Enter
 * and the agent reads key files, writes AGENTS.md and pi-onboard-overview.html.
 *
 * Architecture: AI-driven prompt. Static discovery provides context; the
 * agent provides understanding. We use setEditorText instead of
 * sendUserMessage to avoid stale-ctx errors in co-loaded extensions.
 */
import type { ExtensionAPI, ExtensionCommandContext } from "@earendil-works/pi-coding-agent";
import { getArgumentCompletions, parseArgs, USAGE } from "./flags.ts";
import { discover } from "./discovery.ts";
import { ensureServer, closeServer, type ServerInfo } from "./server.ts";
import type { Options } from "./types.ts";

export default function onboardExtension(pi: ExtensionAPI) {
  // Close any active server on session shutdown (cleanup insurance).
  pi.on("session_shutdown", () => {
    closeServer();
  });

  pi.registerCommand("onboard", {
    description: "Onboard into a repo: generate AGENTS.md and HTML overview",
    getArgumentCompletions,
    handler: async (args: string, ctx: ExtensionCommandContext) => {
      const result = parseArgs(args);

      if (result === null) {
        ctx.ui.notify(USAGE, "info");
        return;
      }

      const warnings = (result as Options & { warnings?: string[] }).warnings ?? [];
      for (const w of warnings) {
        ctx.ui.notify(w, "warning");
      }

      await runOnboard(result, ctx);
    },
  });
}

/**
 * Main flow: discover → start server → build prompt → fill editor.
 * The user presses Enter and the agent does the rest.
 */
async function runOnboard(opts: Options, ctx: ExtensionCommandContext): Promise<void> {
  // 1. Quick static discovery for context
  let repo;
  try {
    repo = discover(ctx.cwd);
  } catch (e) {
    ctx.ui.notify(`pi-onboard: discovery failed — ${e}`, "error");
    return;
  }

  // 2. Start server (unless --no-serve / --text-only)
  let serverInfo: ServerInfo | null = null;
  if (!opts.noServe && !opts.textOnly) {
    try {
      serverInfo = await ensureServer(ctx.cwd, opts);
    } catch (e) {
      ctx.ui.notify(`pi-onboard: failed to start server — ${e}`, "warning");
    }
  }

  // 3. Build the prompt
  const prompt = buildPrompt(repo, opts, serverInfo);

  // 4. Fill the editor so the user can press Enter to send
  ctx.ui.setEditorText(prompt);

  // 5. Notify
  const servingNote = serverInfo
    ? `\n\nServing at:\n${serverInfo.urls.map((u) => `  ${u}`).join("\n")}\n  (bound to 0.0.0.0 — visible to other machines on this network)`
    : "";
  ctx.ui.notify(
    `pi-onboard: press Enter to start the analysis.${servingNote}`,
    "info",
  );
}

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

function buildPrompt(
  repo: ReturnType<typeof discover>,
  opts: Options,
  serverInfo: ServerInfo | null,
): string {
  const lines: string[] = [];

  lines.push("## Onboarding Analysis");
  lines.push("");
  lines.push("Thoroughly understand this repository and generate two onboarding artifacts. Use your tools (read, bash, write, edit) to inspect the repo, then write the files.");
  lines.push("");

  // Discovery context
  lines.push("### Quick discovery (pre-scanned)");
  lines.push("```json");
  lines.push(JSON.stringify({
    name: repo.name,
    description: repo.description,
    runtime: repo.runtime,
    languages: repo.languages.slice(0, 5),
    scripts: repo.scripts,
    dependencies: repo.dependencies,
    devDependencies: repo.devDependencies,
    topDirs: repo.topDirs.map((d) => d.name),
    importantFiles: repo.importantFiles,
    hasExistingContext: repo.hasExistingContext,
  }, null, 2));
  lines.push("```");
  lines.push("");

  // Instructions
  lines.push("### Steps");
  lines.push("1. Read the README, manifests, and key source files to understand what this project actually does.");
  lines.push("2. Identify: project purpose, tech stack, important directories, commands (run/test/lint/build), conventions, entry points.");
  lines.push(`3. Write \`AGENTS.md\` in the repo root${opts.force ? " (overwrite if exists — --force is set)" : " (use draft filename if file already exists)"}.`);
  if (!opts.textOnly) {
    lines.push(`4. Write \`pi-onboard-overview.html\` in the repo root${opts.force ? " (overwrite if exists)" : " (use draft filename if file already exists)"}.`);
  }
  lines.push("");

  // AGENTS.md format
  lines.push("### AGENTS.md format");
  lines.push("Write clean, well-formatted markdown. Lean and practical (50-150 lines). Do NOT include any HTML comments or hidden markers — just plain readable markdown.");
  lines.push("");
  lines.push("```markdown");
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Auto-generated by pi-onboard. Review before committing.");
  lines.push("");
  lines.push("## Project purpose");
  lines.push("(1-3 sentences on what this project actually does — be specific)");
  lines.push("");
  lines.push("## Tech stack");
  lines.push("- TypeScript / Node.js / etc. with versions if known");
  lines.push("- Key frameworks and libraries");
  lines.push("");
  lines.push("## Important paths");
  lines.push("- `dir/` — what's in it and why it matters");
  lines.push("");
  lines.push("## Commands");
  lines.push("- **Run**: `command` — what it does");
  lines.push("- **Test**: `command` — what it does");
  lines.push("- **Lint**: `command` (label uncertain ones as 'likely')");
  lines.push("- **Build**: `command`");
  lines.push("");
  lines.push("## Working conventions");
  lines.push("(patterns and gotchas discovered in the code)");
  lines.push("");
  lines.push("## Where to start when making changes");
  lines.push("1. Read `file` — why");
  lines.push("2. Check `dir/` — why");
  lines.push("");
  lines.push("## Open uncertainties");
  lines.push("(things you couldn't determine — be honest)");
  lines.push("```");
  lines.push("");

  // File safety
  lines.push("### File safety");
  if (opts.force) {
    lines.push("- **--force**: overwrite both files in place if they exist.");
  } else {
    lines.push("- If `AGENTS.md` already exists → write `AGENTS.pi-onboard.draft.md` instead.");
    lines.push("- If `pi-onboard-overview.html` already exists → write `pi-onboard-overview.draft.html` instead.");
  }
  lines.push("");

  // HTML format
  if (!opts.textOnly) {
    lines.push("### HTML overview format");
    lines.push("Single self-contained `pi-onboard-overview.html`:");
    lines.push("- Dark theme, card-based, collapsible sections, embedded CSS, minimal inline JS");
    lines.push("- NO external dependencies or CDNs");
    lines.push("- Sections: summary card, repo structure, commands, conventions, where to start");
    if (serverInfo) {
      lines.push("");
      lines.push("The HTML is being served at:");
      for (const url of serverInfo.urls) {
        lines.push(`- ${url}`);
      }
      lines.push("(server reads the file on each request, so output is live immediately)");
    }
    lines.push("");
  } else {
    lines.push("### Note: --text-only is set, skip HTML entirely.");
    lines.push("");
  }

  lines.push("After writing the files, print a brief summary of what you generated.");

  return lines.join("\n");
}
